# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define :domserver do |ds|
    ds.vm.box = "debian/stretch64"
    ds.vm.hostname = "domserver"
    ds.vm.network "private_network", ip: "192.168.50.2"
    ds.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      # vb.gui = true

      vb.cpus = 2
      # Customize the amount of memory on the VM:
      vb.memory = "2048"
    end

    ds.vm.provision "shell", path: "provision_domserver.sh"
  end

  config.vm.define :judgehost do |jh|
    jh.vm.box = "debian/stretch64"
    jh.vm.hostname = "judgehost"
    jh.vm.network "private_network", ip: "192.168.50.3"
    jh.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      # vb.gui = true

      vb.cpus = 2
      # Customize the amount of memory on the VM:
      vb.memory = "2048"
    end

    jh.vm.provision "shell", path: "provision_judgehost.sh"
  end
end
